const BASE_URL = "http://localhost:8080";

export const API = {
    LOGIN:      `${BASE_URL}/authenticate`,
    SENDMAIL:   `${BASE_URL}/mail/authMail`,
    USERSAVE:   `${BASE_URL}/mail/sendMail`,
    AUTHMAIL:   `${BASE_URL}/users/save`,
    USERUPDATE: `${BASE_URL}/users/update`,
    USERINFO:   `${BASE_URL}/users/info`,
    USERDELETE: `${BASE_URL}/users/delete`,
    LOGOUT:     `${BASE_URL}/users/logout`,
    POSTSMAIN:  `${BASE_URL}/posts/main`,
    LIKEIT:     `${BASE_URL}/posts/likeIt`,
    POSTSSAVE:  `${BASE_URL}/posts/save`,
    POSTSLIKEIT:  `${BASE_URL}/posts/saveL`,
    POSTSDISLIKEIT:  `${BASE_URL}/posts/deleteL`,
    POSTSUPDATE:`${BASE_URL}/posts/update`,
    POSTSDELETE:`${BASE_URL}/posts/delete`,
    EATMAIN:    `${BASE_URL}/eat/main`,
    EATSAVE:    `${BASE_URL}/eat/save`,
    EATDELETE:    `${BASE_URL}/eat/delete`,
    MYFOOD:    `${BASE_URL}/food/myFood`,
    FOODSAVE:   `${BASE_URL}/food/save`,
    FOODDELETE:    `${BASE_URL}/food/delete`,
    FOODSEARCH:    `${BASE_URL}/food/search`,
    REDIRECT:   `${BASE_URL}/reissue`,
    COMMENTSSAVE: `${BASE_URL}/comment/save`,
    COMMENTSMAIN: `${BASE_URL}/comment/posts`,
    COMMENTSDELETE: `${BASE_URL}/comment/delete`
};